# Use the latest Ubuntu base image
FROM ubuntu:latest

# Update APT and upgrade installed packages
RUN apt-get update && apt-get upgrade -y

# Default command to run when container starts
CMD echo "Hello, World!"
